### ISSUE TITLE
Storing login details and other user info

### ISSUE THREAD

**Issue by Jasman04** [Daggerpov/Personal-Banking-Pro#2]

**Comment by Daggerpov** [comment]
we'll want to do this in some kind of file, which I'm thinking .json will be useful for so we can associate certain info under keys to find it

**Comment by Jasman04** [comment]
This will be effected by the authentication screen and the balances of the different accounts

**Comment by Daggerpov** [comment]
I have found [this](https://github.com/fangyidong/json-simple) repository for a tool called JSON simple to use in order to read/write to a file in java. Websites for me to use so I can learn how to use this for our project:
https://stackabuse.com/reading-and-writing-json-in-java/
https://howtodoinjava.com/java/library/json-simple-read-write-json-examples/

**Comment by Daggerpov** [comment]
This will be done in JSON one way or another, however, I'm considering running a Python script to do it for me since I'm used to doing so in this language and all the java solutions don't seem to be working due to Maven dependency issues. All in all, we're not being marked on this part so I figure it should be fine project-wise but for future Java projects, I know now how to initially setup the project using Maven properly.

**Comment by Daggerpov** [comment]
got balance to show up throughout program, the rest should be easy to do, albeit without the ability to save information across runs of the program. This is a compromise we've decided to make due to the difficulty we ran into with editing .JSON files (within Java, since it was fairly straightforward in Python for me).
